### ISSUE TITLE
Opencv

### ISSUE THREAD

**Issue by godisboy** [huangynn/FaceEngine#1]
I want to know which version of Opencv you uesd in this Lib.
Because I got some problem with Opencv lib included.
Thanks!

**Comment by huangynn** [comment]
The version I use is 3.1.0  @godisboy 

what's the problem you encountered? Can you describe in detail?

**Comment by huangynn** [comment]
And you I used some modules in opencv/contrib, you should also install the contrib module.
After opencv 3.0, some modules are extracted to contrib, which needs extra installation.

@godisboy

**Comment by godisboy** [comment]
Thanks！ I’ve solved the problem. I used to apply opencv 3.0 which miss some modules included in your code. @huangynn
